/**
 * Two variants of one vocabulary. The groups below (animation, gradient, boxShadow,
 * form, button, panel) come from the shared component kit, the first seven colours
 * are this site's own palette.
 *
 * Note on `white` and `black`: the kit uses them as surface tokens rather than as
 * literal colours, so in the dark variant they are swapped - otherwise every panel
 * and dropdown copied from the kit would stay white on a dark page.
 */
const light = {
  background: '#ffffff',
  foreground: '#18181b',
  muted: '#f5f5f6',
  mutedForeground: '#71717a',
  edge: '#e4e4e7',
  accent: '#f1f1f3',
  online: '#15ba81',

  theme: '#3b82f6',
  border: '#e5e7eb',
  grey: '#eeeeee',
  darkGrey: '#9ca3af',
  white: '#ffffff',
  black: '#000000',
  blue: '#1f2937',
  text: {
    primary: '#333333',
    light: '#666666',
    disabled: '#999999',
  },
  green: {
    default: '#28a745',
    light: '#e8f5e8',
    dark: '#2d5a2d',
  },
  red: {
    default: '#ff0000',
    light: '#f8d7da',
    dark: '#721c24',
  },
  orange: {
    default: '#f59e0b',
    light: '#fff3cd',
    dark: '#856404',
    bright: '#ffc107',
  },
};

const dark: typeof light = {
  background: '#0d0d0f',
  foreground: '#f2f2f2',
  muted: '#1a1a1d',
  mutedForeground: '#919199',
  edge: '#2b2b2f',
  accent: '#1d1d20',
  online: '#1bcc8e',

  theme: '#60a5fa',
  border: '#2b2b2f',
  grey: '#1a1a1d',
  darkGrey: '#6b7280',
  white: '#0d0d0f',
  black: '#f2f2f2',
  blue: '#e5e7eb',
  text: {
    primary: '#f2f2f2',
    light: '#919199',
    disabled: '#6b7280',
  },
  green: {
    default: '#2ecc71',
    light: '#14301f',
    dark: '#8ce0ae',
  },
  red: {
    default: '#f87171',
    light: '#3a1416',
    dark: '#fca5a5',
  },
  orange: {
    default: '#fbbf24',
    light: '#3a2c0d',
    dark: '#fcd34d',
    bright: '#fde047',
  },
};

const form = (colors: typeof light) => ({
  label: {
    color: colors.text.primary,
  },
  control: {
    minHeight: '56px',
    background: colors.white,
    color: colors.text.primary,
    border: colors.border,
    placeholder: colors.text.light,
    focus: {
      border: colors.theme,
    },
    error: {
      background: colors.red.light,
      border: colors.red.default,
    },
    disabled: {
      color: colors.text.disabled,
      border: colors.border,
    },
  },
  error: {
    color: colors.red.default,
  },
});

const button = (colors: typeof light) => ({
  minHeight: '56px',
  primary: {
    background: colors.theme,
    color: colors.white,
    white: {
      background: colors.white,
      color: colors.theme,
    },
    green: { background: colors.green.default },
    red: { background: colors.red.default },
    grey: { background: colors.darkGrey },
  },
  ghost: {
    border: colors.theme,
    color: colors.theme,
    hover: {
      background: colors.accent,
    },
    white: {
      border: colors.white,
      color: colors.white,
      hover: {
        background: colors.white,
        color: colors.theme,
      },
    },
    green: {
      border: colors.green.default,
      color: colors.green.default,
      hover: {
        background: colors.green.light,
        color: colors.green.default,
      },
    },
    red: {
      border: colors.red.default,
      color: colors.red.default,
      hover: {
        background: colors.red.light,
        color: colors.red.default,
      },
    },
    grey: {
      border: colors.darkGrey,
      color: colors.darkGrey,
      hover: {
        background: colors.grey,
        color: colors.darkGrey,
      },
    },
  },
});

const panel = (colors: typeof light) => ({
  default: {
    color: colors.white,
    background: colors.theme,
  },
  error: {
    color: colors.white,
    background: colors.red.default,
  },
  warning: {
    color: colors.white,
    background: colors.orange.default,
  },
});

const animation = {
  duration: '0.3s',
};

const container = {
  maxWidth: '1260px',
};

const gradient = {
  base: {
    degree: '135deg',
    start: '#3b82f6',
    end: '#1e40af',
  },
  background: {
    degree: '135deg',
    start: '#667eea',
    end: '#764ba2',
  },
};

/** Generated by next/font, so they are real CSS variables rather than values. */
export const font = {
  sans: 'var(--font-sans)',
  mono: 'var(--font-mono)',
};

const headerHeightPx = 56;

export const layout = {
  contentWidth: '768px',
  headerHeightPx,
  headerHeight: `${headerHeightPx}px`,
};

export const media = {
  small: '@media (min-width: 640px)',
};

const build = (colors: typeof light, shadow: string) => ({
  colors,
  form: form(colors),
  button: button(colors),
  panel: panel(colors),
  boxShadow: { panel: shadow },
  animation,
  container,
  gradient,
  font,
  layout,
  media,
});

export const themes = {
  light: build(light, '0 4px 12px rgba(0, 0, 0, 0.15)'),
  dark: build(dark, '0 4px 12px rgba(0, 0, 0, 0.6)'),
};

export type TTheme = (typeof themes)['light'];

export default themes;
